name = "Diary"
license = "MIT"
licenselink = "https://github.com/amazingrise/hugo-theme-diary/blob/master/LICENSE"
description = "Moments piled up. A simple, elegant blog theme."
homepage = "https://amazingrise.net/"
tags = ["blog"]
features = ["mobile","elegant"]
min_version = "0.59.0"

[author]
  name = "Kip Jinag"
  homepage = "https://kipjiang.github.io"
  repo = "https://github.com/KipJiang/diary"

[original.v2]
  name = "amazingrise"
  homepage = "https://amazingrise.net/"

# If porting an existing theme
[original.v1]
  name = "SumiMakito"
  homepage = "https://mak1t0.cc"
  repo = "https://github.com/SumiMakito/hexo-theme-Journal/"
