baseURL = "http://example.org/"
DefaultContentLanguage = "en" # Theme's display language, supports: en, fr, zh, zh-hant
languageCode = "en-us"
title = "My Blog"
copyright = "This is a customized copyright." # you can use markdown syntax.
description = "My HomePage Description"  # will set 'og:description'

theme = "diary"
# Twitter Card and Open Graph settings
enableOpenGraph = true
enableTwitterCards = true
# googleAnalytics = "UA-123-45"
# enableEmoji = true

[params]
subtitle = "Themed by Diary."
favicon = "favicon.ico"
enableMathJax = true
enableReadingTime=true
# googleSearchCode = "Your Search Code"

[taxonomies]
   tag = "tags"
   category = "categories"

[permalinks]
    posts = "/post/:year/:month/:day/:slug/"

[[menu.main]]
url = "/about"
name = "About"
weight = 1
[[menu.main]]
url = "/posts"
name = "Blogs"
weight = 2
[[menu.main]]
url = "/categories"
name = "Categories"
weight = 3
[[menu.main]]
url = "/tags"
name = "Tags"
weight = 4
# [[menu.main]]
# url = "/archive"
# name = "Archive"
# weight = 5

[params.valine]
enableValine = false
appId = 'xxx'
appKey = 'yyy'
placeholder = 'Say something... (please fill in the email to receive the reply)'
requiredFields = ['nick','mail']
avatar = 'robohash'
visitor = true

[params.social]
github = 'https://github.com/KipJiang'
facebook = 'http://example.org/'
twitter = 'http://example.org/'
instagram = 'http://example.org/'
linkedin = 'http://example.org/'
weibo = 'http://example.org/'

# doc: https://gohugo.io/getting-started/configuration-markup#highlight
# syntax style: https://xyproto.github.io/splash/docs/longer/all.html
[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai" # github, dracula, vim, monokai
    tabWidth = 4